# Generated by Django 4.2.11 on 2024-05-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='actividades_propio_centro',
        ),
        migrations.RemoveField(
            model_name='director',
            name='after_school_descripcion',
        ),
        migrations.RemoveField(
            model_name='director',
            name='after_school_existencia',
        ),
        migrations.RemoveField(
            model_name='director',
            name='after_school_participacion_1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='asignaturas_ingles_dictadas',
        ),
        migrations.RemoveField(
            model_name='director',
            name='asignaturas_ingles_plan_estudios',
        ),
        migrations.RemoveField(
            model_name='director',
            name='cantidad_estudiantes_actividades_centro_1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='cantidad_estudiantes_actividades_especiales_1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='cantidad_estudiantes_actividades_externas_1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='codigos_plan_estudio',
        ),
        migrations.RemoveField(
            model_name='director',
            name='correo_personal1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='correo_personal2',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes2',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes3',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes4',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes_aprobados_ppb',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes_asignatura',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes_capacitacion_exterior',
        ),
        migrations.RemoveField(
            model_name='director',
            name='docentes_capacitados_ppb',
        ),
        migrations.RemoveField(
            model_name='director',
            name='estudiantes_nivel_ppb',
        ),
        migrations.RemoveField(
            model_name='director',
            name='estudiantes_salon',
        ),
        migrations.RemoveField(
            model_name='director',
            name='femenino1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='femenino2',
        ),
        migrations.RemoveField(
            model_name='director',
            name='femenino3',
        ),
        migrations.RemoveField(
            model_name='director',
            name='femenino4',
        ),
        migrations.RemoveField(
            model_name='director',
            name='grado1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='grado2',
        ),
        migrations.RemoveField(
            model_name='director',
            name='grado3',
        ),
        migrations.RemoveField(
            model_name='director',
            name='grado4',
        ),
        migrations.RemoveField(
            model_name='director',
            name='masculino1',
        ),
        migrations.RemoveField(
            model_name='director',
            name='masculino2',
        ),
        migrations.RemoveField(
            model_name='director',
            name='masculino3',
        ),
        migrations.RemoveField(
            model_name='director',
            name='masculino4',
        ),
        migrations.RemoveField(
            model_name='director',
            name='matricula_total',
        ),
        migrations.RemoveField(
            model_name='director',
            name='nivel_escolar',
        ),
        migrations.RemoveField(
            model_name='director',
            name='participa_ppb',
        ),
        migrations.RemoveField(
            model_name='director',
            name='planes_clase',
        ),
        migrations.RemoveField(
            model_name='director',
            name='planes_estudio',
        ),
        migrations.RemoveField(
            model_name='director',
            name='total_docentes',
        ),
        migrations.AddField(
            model_name='director',
            name='acceso_internet_softwares',
            field=models.CharField(blank=True, choices=[('no_requieren', 'No requieren'), ('si_requieren', 'Sí requieren')], default='no_requieren', max_length=13),
        ),
        migrations.AddField(
            model_name='director',
            name='acceso_wifi_administrativos',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='acceso_wifi_docentes',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='acceso_wifi_estudiantes',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='actividades_ingles',
            field=models.CharField(choices=[('nunca', 'Nunca o Casi Nunca'), ('algunas_veces', 'Algunas veces'), ('muchas_veces', 'Muchas veces'), ('siempre', 'Siempre o Casi Siempre')], default='si', max_length=20, verbose_name='¿Se realizan actividades especiales que promueven el aprendizaje y uso del idioma inglés que nacen desde su Centro Educativo?'),
        ),
        migrations.AddField(
            model_name='director',
            name='acuarelas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='ajuste_plan_estudios',
            field=models.CharField(choices=[('muy_en_desacuerdo', 'Muy en desacuerdo'), ('en_desacuerdo', 'En desacuerdo'), ('de_acuerdo', 'De acuerdo'), ('muy_de_acuerdo', 'Muy de acuerdo')], default='de_acuerdo', max_length=20, verbose_name='Ajuste del Plan de Estudios'),
        ),
        migrations.AddField(
            model_name='director',
            name='alcance_wifi',
            field=models.CharField(blank=True, choices=[('cobertura_parcial', 'Cobertura Parcial'), ('cobertura_completa', 'Cobertura Completa')], default='cobertura_parcial', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='ancho_banda',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='ano_fabricacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='asignaturas_ingles_centro_educativo',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name='Asignaturas en Inglés en Centro Educativo'),
        ),
        migrations.AddField(
            model_name='director',
            name='asignaturas_ingles_plan_estudio',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name='Asignaturas en Inglés en Plan de Estudios'),
        ),
        migrations.AddField(
            model_name='director',
            name='boligrafos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='cantidad_docentes_asignatura',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='cantidad_salones_laboratorios',
            field=models.CharField(blank=True, choices=[('no_es_posible_responder', 'No es posible responder'), ('1-2', 'Hay 1-2'), ('3-4', 'Hay 3-4'), ('5_o_mas', 'Hay 5 o más')], default='no_es_posible_responder', max_length=25),
        ),
        migrations.AddField(
            model_name='director',
            name='carpetas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='cartuchos_tinta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='cartulinas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='cds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='centro_educativo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='computadora',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='cooperacion_participacion_ppb',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name='Cooperación y participación entre profesores capacitados en PPB'),
        ),
        migrations.AddField(
            model_name='director',
            name='cooperacion_participacion_ppb_no_ppb',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name='Cooperación y participación entre profesores capacitados en PPB y los profesores no capacitados en el Programa'),
        ),
        migrations.AddField(
            model_name='director',
            name='correo_personal',
            field=models.EmailField(default='N/A@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='director',
            name='cuadernos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='cuenta_con_internet',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='curso_ingles_after_school',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name="Cursos de inglés tipo 'After School'"),
        ),
        migrations.AddField(
            model_name='director',
            name='cursos_after_school',
            field=models.TextField(default='Curso 1, Curso 2', verbose_name="Cursos de inglés tipo 'After School' mencionados"),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_1',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_10',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_11',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_12',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_2',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_3',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_4',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_5',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_6',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_7',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_8',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_grado_9',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_kinder',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='docentes_capacitados_prekinder',
            field=models.CharField(blank=True, choices=[('1-5', '1 - 5'), ('6-10', '6 - 10'), ('11-15', '11 - 15'), ('15+', '15+')], default='1-5', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='dvds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_cursos_after_school',
            field=models.IntegerField(default=0, verbose_name='Estudiantes participantes en cursos After school por grado'),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_1',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_10',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_11',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_12',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_2',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_3',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_4',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_5',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_6',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_7',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_8',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_grado_9',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_kinder',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='estudiantes_ppb_prekinder',
            field=models.CharField(blank=True, choices=[('1-20', '1 - 20'), ('21-40', '21 - 40'), ('41-60', '41 - 60'), ('61-80', '61 - 80'), ('80+', '80 a más')], default='1-20', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='femenino_kinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='femenino_prekinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='folios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='frecuencia_ingles_clase',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='geolocalizacion',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='gomas_borrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='grado',
            field=models.CharField(choices=[('pre_kinder', 'Pre Kinder'), ('kinder', 'Kinder'), ('1', '1° Grado'), ('2', '2° Grado'), ('3', '3° Grado'), ('4', '4° Grado'), ('5', '5° Grado'), ('6', '6° Grado'), ('7', '7° Grado'), ('8', '8° Grado'), ('9', '9° Grado'), ('10', '10° Grado'), ('11', '11° Grado'), ('12', '12° Grado')], default='pre_kinder', max_length=20, verbose_name='Grado'),
        ),
        migrations.AddField(
            model_name='director',
            name='incentivo_ingles_clase',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='interes_formacion_bilingue',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='kinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='laboratorio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='laboratorio_idioma_ingles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='laboratorio_ingles_informatica_mismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='lapices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='libretas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='licencias_softwares',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='masculino_kinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='masculino_prekinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='material_multimedia',
            field=models.CharField(blank=True, choices=[('muy_en_desacuerdo', 'Muy en desacuerdo'), ('desacuerdo', 'Desacuerdo'), ('de_acuerdo', 'De acuerdo'), ('muy_de_acuerdo', 'Muy de acuerdo')], default='muy_en_desacuerdo', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='materiales_ingles',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='materiales_multimedia',
            field=models.CharField(blank=True, choices=[('muy_en_desacuerdo', 'Muy en desacuerdo'), ('desacuerdo', 'Desacuerdo'), ('de_acuerdo', 'De acuerdo'), ('muy_de_acuerdo', 'Muy de acuerdo')], default='muy_en_desacuerdo', max_length=20),
        ),
        migrations.AddField(
            model_name='director',
            name='matricula_total_estudiantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='medio_compra',
            field=models.CharField(choices=[('fondos_fece', 'Fondos de FECE'), ('asociacion_padres', 'Asociación de padres de familia'), ('estudiantes_traen', 'Los estudiantes los traen'), ('fondos_propios', 'Fondos propios (del director o docente)'), ('otro', 'Otro')], default='fondos_fece', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='niveles_educativos',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='director',
            name='nombre_centro_valido',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='nombre_encargado_capacitacion',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='nombre_encargado_laboratorios',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='nombre_encargado_material',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='nombre_encargado_panama_bilingue',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='nombre_encargado_verificacion',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='numero_estudiantes_salon',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='otro_medio_compra',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='papel_celofan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='participa_activamente_ppb',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='participacion',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('algunos', 'Algunos'), ('alrededor_mitad', 'Alrededor de la mitad'), ('mas_mitad', 'Más de la mitad'), ('todos', 'Todos')], default='ninguno', max_length=20, verbose_name='Participación de Estudiantes'),
        ),
        migrations.AddField(
            model_name='director',
            name='participacion_estudiantes',
            field=models.CharField(choices=[('nunca', 'Nunca o Casi Nunca'), ('algunas_veces', 'Algunas veces'), ('muchas_veces', 'Muchas veces'), ('siempre', 'Siempre o Casi Siempre')], default='siempre', max_length=20, verbose_name='¿Cuantos estudiantes participan actualmente en estas actividades por grado?'),
        ),
        migrations.AddField(
            model_name='director',
            name='pegamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='percepcion_velocidad',
            field=models.CharField(blank=True, choices=[('muy_mala', 'Muy Mala'), ('mala', 'Mala'), ('regular', 'Regular'), ('buena', 'Buena'), ('muy_buena', 'Muy Buena')], default='muy_mala', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='persona_encargada_capacitacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='persona_encargada_laboratorios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='persona_encargada_material',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='persona_encargada_panama_bilingue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='persona_encargada_verificacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='pinceles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='pinturas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='pipetas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='planes_estudio_2023_disponibles',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name='Planes de Estudio 2023 Disponibles'),
        ),
        migrations.AddField(
            model_name='director',
            name='planes_estudio_disponibles',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name='Planes de Estudio Disponibles'),
        ),
        migrations.AddField(
            model_name='director',
            name='plastilina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='porcentaje_ingles_clase',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='pregunta_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='director',
            name='prekinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='director',
            name='prioridad_ppb',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='probetas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='promocion_ingles_estudiantes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='recursos_enseñanza_ingles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='recursos_multimedia',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='responsabilidad_docentes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='rotuladores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='salones_laboratorios_informatica',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2),
        ),
        migrations.AddField(
            model_name='director',
            name='senalizaciones_ingles',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='si', max_length=2, verbose_name='Señalizaciones en Inglés'),
        ),
        migrations.AddField(
            model_name='director',
            name='senialetica_ingles',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='sobres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='software_ingles',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='director',
            name='software_ingles_cantidad',
            field=models.CharField(blank=True, choices=[('0', '0 (No hay)'), ('1', '1 (Hay)'), ('2', '2 (Hay)'), ('mas_de_2', 'Más de 2')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='software_ingles_nombres',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='tiene_auriculares',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='tiene_bocina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='tiene_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='tiene_microfono',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='tijeras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='tipo_enlace_internet',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='tizas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='toner_impresoras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='total_docentes_media_10',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='total_docentes_media_11',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='total_docentes_media_12',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='director',
            name='tubos_ensayo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='usuarios_disponibles',
            field=models.CharField(blank=True, choices=[('0', '0 (No hay)'), ('uno_por_estudiante', 'Uno por estudiante'), ('menos_de_uno_por_estudiante', 'Menos de uno por estudiante (comparten licencia)')], default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='director',
            name='wifi_cobertura',
            field=models.CharField(blank=True, choices=[('0-24', '0 - 24%'), ('25-49', '25 - 49%'), ('50-74', '50 - 74%'), ('75-100', '75 - 100%')], default='0-24', max_length=7),
        ),
        migrations.AddField(
            model_name='director',
            name='wifi_solucion_existencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='director',
            name='actividades_externas_centro',
            field=models.CharField(choices=[('nunca', 'Nunca o Casi Nunca'), ('algunas_veces', 'Algunas veces'), ('muchas_veces', 'Muchas veces'), ('siempre', 'Siempre o Casi Siempre')], default='si', max_length=20, verbose_name='¿Se realizan actividades especiales que promueven el aprendizaje y uso del idioma inglés que nacen desde fundaciones, otras instituciones, empresa privada u otros organismos que se realizan en su Centro Educativo?'),
        ),
        migrations.AlterField(
            model_name='director',
            name='actividades_meduca_centro',
            field=models.CharField(choices=[('nunca', 'Nunca o Casi Nunca'), ('algunas_veces', 'Algunas veces'), ('muchas_veces', 'Muchas veces'), ('siempre', 'Siempre o Casi Siempre')], default='si', max_length=20, verbose_name='¿Se realizan actividades especiales que promueven el aprendizaje y uso del idioma inglés que nacen desde MEDUCA y se realizan en su Centro Educativo?'),
        ),
        migrations.AlterField(
            model_name='director',
            name='detalle_actividades_anual',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='director',
            name='horas_ingles',
            field=models.CharField(choices=[('1-5', '1-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('15+', '15+')], default='1-5', max_length=5, verbose_name='Horas dedicadas a la enseñanza del inglés'),
        ),
        migrations.AlterField(
            model_name='director',
            name='horas_practicas',
            field=models.CharField(choices=[('1-5', '1-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('15+', '15+')], default='1-5', max_length=5, verbose_name='Horas prácticas impartidas dentro del plan de estudio'),
        ),
        migrations.AlterField(
            model_name='director',
            name='horas_teoricas',
            field=models.CharField(choices=[('1-5', '1-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('15+', '15+')], default='1-5', max_length=5, verbose_name='Horas teóricas impartidas dentro del plan de estudio'),
        ),
        migrations.AlterField(
            model_name='director',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
